name: Make a fix
run-name: ${{ github.actor }} is fixing a release
on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        required: true
        description: "Version to release"
      issue-number:
        type: number
        required: true
        description: "Issue number id"

jobs:
  lint_and_test:
    uses: ./.github/workflows/lint-test.yml

  fix_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release/${{ inputs.release_version }}

      - name: Login to Yandex Container Registry
        run: |
          echo ${{ secrets.AUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

      - name: Create Docker image Fix
        run: |
          docker build -t cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ inputs.release_version }}_fix${{ github.run_number }} .
          docker push cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ inputs.release_version }}_fix${{ github.run_number }}

      - name: Create Docker image Latest
        run: |
          docker build -t cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ inputs.release_version }}_latest .
          docker push cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ inputs.release_version }}_latest

  create_tag:
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release/${{inputs.release_version}}

      - name: Push tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ inputs.release_version }}_fix${{ github.run_number }}
          
  add_comment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Write date into a variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{inputs.issue-number}}
          body: |
            **Fix**:
            - Date: ${{env.NOW}}
            - Author: ${{ github.triggering_actor }}
            - Version: ${{ github.run_number }}
            - Commits:
            - YCR Docker Image: cr.yandex/${{secrets.REGISTRY_ID}}/app:${{ inputs.release_version }}_fix${{ github.run_number }}
