name: Make a release
run-name: ${{ github.actor }} is making a release
on:
  workflow_dispatch:
  
jobs:
  lint_and_test:
    uses: ./.github/workflows/lint-test.yml

  create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create release branch
        run: |
          git checkout -b release/${{ github.run_number }}
          git push origin release/${{ github.run_number }}

      - name: Build docker image
        run: docker build -t cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ github.run_number }} -t cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ github.run_number }}_latest .

      - name: Push Docker image
        run: |
          echo ${{ secrets.AUTH_TOKEN }} | docker login cr.yandex -u oauth --password-stdin
          docker push cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ github.run_number }}_latest

  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release/${{github.run_number}}

      - name: Push tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{github.run_number}}

  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release ${{github.run_number}}
          body: |
            ## Release ${{github.run_number}}: Issue:
            
            - Date: ${{ env.NOW }}
            - Author: ${{ github.triggering_actor }}
            - Version: ${{ github.run_number }}
            - Commits:
            - YCR Docker Image: cr.yandex/${{secrets.REGISTRY_ID}}/app:${{ github.run_number }}
